server:
  port: "8082"
  readTimeoutSeconds: 10
  writeTimeoutSeconds: 10
  idleTimeoutSeconds: 60

database:
  host: "localhost"
  port: "5432"
  user: "postgres"
  password: "postgres"
  dbname: "nfc_card"
  sslmode: "disable"

adapters:
  douyin:
    clientKey: "your_douyin_client_key"
    clientSecret: "your_douyin_client_secret"
    redirectUri: "http://localhost:8082/api/v1/callback/douyin"
  kuaishou:
    appId: "your_kuaishou_app_id"
    appSecret: "your_kuaishou_app_secret"
    callbackUrl: "http://localhost:8082/api/v1/callback/kuaishou"
  xiaohongshu:
    appId: "your_xiaohongshu_app_id"
    appSecret: "your_xiaohongshu_app_secret"
    callbackUrl: "http://localhost:8082/api/v1/callback/xiaohongshu"
  wechat:
    appId: "your_wechat_app_id"
    appSecret: "your_wechat_app_secret"
    token: "your_wechat_token"
  tempDir: "/tmp/distribution-service"

storage:
  type: "s3"
  s3Bucket: "nfc-videos"
  s3Region: "us-west-1"
  s3AccessKey: "your_s3_access_key"
  s3SecretKey: "your_s3_secret_key" 