apisix:
  node_listen: 9080
  enable_admin: true
  enable_admin_cors: true
  admin_listen:
    ip: 0.0.0.0
    port: 9180
  ssl:
    enable: true
    listen_port: 9443
  enable_standalone: true
  enable_sync_validator: false
  use_etcd: false
  allow_plugins_adds: true
  sync_local_conf_to_etcd: false

deployment:
  admin:
    allow_admin:
      - 127.0.0.0/24
      - 0.0.0.0/0
    admin_key:
      - name: "admin"
        key: edd1c9f034335f136f87ad84b625c8f1
        role: admin

plugins:
  - cors
  - jwt-auth
  - limit-req
  - limit-count
  - prometheus
  - request-id
  - response-rewrite
  - proxy-rewrite
  - traffic-split
  - zipkin

# 以下是预配置的路由
routes:
  -
    uri: /api/v1/nfc-cards/*
    upstream:
      type: roundrobin
      nodes:
        "nfc-service:8083": 1
    plugins:
      jwt-auth:
        header: Authorization
        query: token
        cookie: jwt
        hide_credentials: true
      cors:
        allow_origins: "*"
        allow_methods: "GET,POST,PUT,DELETE,PATCH,OPTIONS"
        allow_headers: "Content-Type,Authorization,X-Tenant-ID"
        expose_headers: "Content-Length,Content-Encoding,Content-Type"
        max_age: 3600
        allow_credential: true
  -
    uri: /api/v1/short-links/*
    upstream:
      type: roundrobin
      nodes:
        "nfc-service:8083": 1
    plugins:
      jwt-auth:
        header: Authorization
        query: token
        cookie: jwt
        hide_credentials: true
      cors:
        allow_origins: "*"
        allow_methods: "GET,POST,PUT,DELETE,PATCH,OPTIONS"
        allow_headers: "Content-Type,Authorization,X-Tenant-ID"
        expose_headers: "Content-Length,Content-Encoding,Content-Type"
        max_age: 3600
        allow_credential: true
  -
    uri: /api/v1/merchants/*
    upstream:
      type: roundrobin
      nodes:
        "merchant-service:8082": 1
    plugins:
      jwt-auth:
        header: Authorization
        query: token
        cookie: jwt
        hide_credentials: true
      cors:
        allow_origins: "*"
        allow_methods: "GET,POST,PUT,DELETE,PATCH,OPTIONS"
        allow_headers: "Content-Type,Authorization,X-Tenant-ID"
        expose_headers: "Content-Length,Content-Encoding,Content-Type"
        max_age: 3600
        allow_credential: true
  -
    uri: /api/v1/users/*
    upstream:
      type: roundrobin
      nodes:
        "merchant-service:8082": 1
    plugins:
      jwt-auth:
        header: Authorization
        query: token
        cookie: jwt
        hide_credentials: true
      cors:
        allow_origins: "*"
        allow_methods: "GET,POST,PUT,DELETE,PATCH,OPTIONS"
        allow_headers: "Content-Type,Authorization,X-Tenant-ID"
        expose_headers: "Content-Length,Content-Encoding,Content-Type"
        max_age: 3600
        allow_credential: true
  -
    uri: /api/v1/publish/*
    upstream:
      type: roundrobin
      nodes:
        "distribution-service:8082": 1
    plugins:
      jwt-auth:
        header: Authorization
        query: token
        cookie: jwt
        hide_credentials: true
      cors:
        allow_origins: "*"
        allow_methods: "GET,POST,PUT,DELETE,PATCH,OPTIONS"
        allow_headers: "Content-Type,Authorization,X-Tenant-ID"
        expose_headers: "Content-Length,Content-Encoding,Content-Type"
        max_age: 3600
        allow_credential: true
  -
    uri: /api/v1/stats/*
    upstream:
      type: roundrobin
      nodes:
        "stats-service:8084": 1
    plugins:
      jwt-auth:
        header: Authorization
        query: token
        cookie: jwt
        hide_credentials: true
      cors:
        allow_origins: "*"
        allow_methods: "GET,POST,PUT,DELETE,PATCH,OPTIONS"
        allow_headers: "Content-Type,Authorization,X-Tenant-ID"
        expose_headers: "Content-Length,Content-Encoding,Content-Type"
        max_age: 3600
        allow_credential: true
  -
    uri: /api/v1/auth/*
    upstream:
      type: roundrobin
      nodes:
        "merchant-service:8082": 1
    plugins:
      cors:
        allow_origins: "*"
        allow_methods: "GET,POST,PUT,DELETE,PATCH,OPTIONS"
        allow_headers: "Content-Type,Authorization,X-Tenant-ID"
        expose_headers: "Content-Length,Content-Encoding,Content-Type"
        max_age: 3600
        allow_credential: true
  -
    uri: /api/*
    upstream:
      type: roundrobin
      nodes:
        "merchant-service:8082": 1
    plugins:
      cors:
        allow_origins: "*"
        allow_methods: "GET,POST,PUT,DELETE,PATCH,OPTIONS"
        allow_headers: "Content-Type,Authorization,X-Tenant-ID"
        expose_headers: "Content-Length,Content-Encoding,Content-Type"
        max_age: 3600
        allow_credential: true 