version: '3'

services:
  # API网关
  apisix:
    image: apache/apisix:3.6.0-debian
    ports:
      - "9080:9080"
      - "9443:9443"
    environment:
      - APISIX_STAND_ALONE=true
      - APISIX_ADMIN_KEY=edd1c9f034335f136f87ad84b625c8f1
      - APISIX_ENABLE_ADMIN=true
      - APISIX_ADMIN_LISTEN_PORT=9180
    networks:
      - nfc_network

  # 商户服务
  merchant-service:
    image: nfc-merchant-service
    ports:
      - "8082:8082"
    volumes:
      - ./config:/app/config:ro
    environment:
      - SERVER_PORT=8082
      - CONFIG_PATH=/app/config/merchant-service.yaml
    networks:
      - nfc_network

networks:
  nfc_network:
    driver: bridge 